name:               "KimJinWoo"
description:        "꿈꾸는 개발자"

url:                ""
author:             "JINWOOKIM7"
email:              "maskseven7@naver.com"
gravatar_hash:      "203a05189c7b7c5158e53363c0582b87"
twitter:            "maskseven7"
email:              "maskseven7@naver.com"
github:             "JINWOOKIM7"
pinterest:          "JINWOOKIM7"
linkedin:           "JINWOOKIM7"
facebook:           "JINWOOKIM7"

disqus_shortname:   "JINWOOKIM7"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-10003.jpg"

paginate:           0
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate

encoding: "utf-8"